#!/bin/bash
#
# Setup CRON jobs for autonomous Gauge operation
#
# This script will add CRON entries for:
# - Autonomous Bluesky posting (3x daily: 9am, 2pm, 8pm PST)
# - Autonomous research (every 4 hours)
#
# Usage:
#   ./setup_cron.sh [--dry-run] [--remove]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_PATH="$SCRIPT_DIR/.venv"
PYTHON="$VENV_PATH/bin/python3"

# Log files
POSTER_LOG="$SCRIPT_DIR/logs/autonomous_poster.log"
RESEARCH_LOG="$SCRIPT_DIR/logs/autonomous_research.log"

# Create logs directory
mkdir -p "$SCRIPT_DIR/logs"

# CRON entries
# Note: Times are in PST (UTC-8)
# 9am PST = 17:00 UTC
# 2pm PST = 22:00 UTC
# 8pm PST = 04:00 UTC (next day)

read -r -d '' CRON_ENTRIES << 'EOF' || true
# Gauge Autonomous Operation
# Generated by setup_cron.sh

# Autonomous Bluesky posting - 3x daily (9am, 2pm, 8pm PST)
0 17 * * * cd SCRIPT_DIR && VENV_PATH/bin/python3 autonomous_poster.py >> POSTER_LOG 2>&1
0 22 * * * cd SCRIPT_DIR && VENV_PATH/bin/python3 autonomous_poster.py >> POSTER_LOG 2>&1
0 4 * * * cd SCRIPT_DIR && VENV_PATH/bin/python3 autonomous_poster.py >> POSTER_LOG 2>&1

# Autonomous research - every 4 hours
0 */4 * * * cd SCRIPT_DIR && VENV_PATH/bin/python3 autonomous_research.py research >> RESEARCH_LOG 2>&1
EOF

# Replace placeholders
CRON_ENTRIES="${CRON_ENTRIES//SCRIPT_DIR/$SCRIPT_DIR}"
CRON_ENTRIES="${CRON_ENTRIES//VENV_PATH/$VENV_PATH}"
CRON_ENTRIES="${CRON_ENTRIES//POSTER_LOG/$POSTER_LOG}"
CRON_ENTRIES="${CRON_ENTRIES//RESEARCH_LOG/$RESEARCH_LOG}"

show_help() {
    cat << HELP
Setup CRON jobs for autonomous Gauge operation

Usage:
    ./setup_cron.sh [options]

Options:
    --dry-run    Show what would be added to crontab without modifying
    --remove     Remove Gauge CRON entries from crontab
    --help       Show this help message

Examples:
    ./setup_cron.sh              # Install CRON jobs
    ./setup_cron.sh --dry-run    # Preview changes
    ./setup_cron.sh --remove     # Uninstall CRON jobs

CRON Schedule:
    Posting:  9am, 2pm, 8pm PST (3x daily)
    Research: Every 4 hours

Logs:
    Posting:  $POSTER_LOG
    Research: $RESEARCH_LOG
HELP
}

# Check if Python and venv exist
check_prerequisites() {
    if [[ ! -f "$PYTHON" ]]; then
        echo "Error: Python venv not found at $VENV_PATH"
        echo "Run: python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt"
        exit 1
    fi
    
    if [[ ! -f "$SCRIPT_DIR/config.yaml" ]]; then
        echo "Error: config.yaml not found"
        echo "Run: python setup.py"
        exit 1
    fi
    
    echo "✓ Prerequisites check passed"
}

# Add CRON entries
install_cron() {
    echo "Installing CRON jobs..."
    
    # Get current crontab
    CURRENT_CRON=$(crontab -l 2>/dev/null || true)
    
    # Check if already installed
    if echo "$CURRENT_CRON" | grep -q "Gauge Autonomous Operation"; then
        echo "Warning: Gauge CRON entries already exist"
        echo "Run with --remove first to reinstall"
        exit 1
    fi
    
    # Add new entries
    {
        echo "$CURRENT_CRON"
        echo ""
        echo "$CRON_ENTRIES"
    } | crontab -
    
    echo "✓ CRON jobs installed successfully"
    echo ""
    echo "Schedule:"
    echo "  Posting:  9am, 2pm, 8pm PST (3x daily)"
    echo "  Research: Every 4 hours"
    echo ""
    echo "View with: crontab -l"
    echo "Remove with: ./setup_cron.sh --remove"
}

# Remove CRON entries
remove_cron() {
    echo "Removing CRON jobs..."
    
    # Get current crontab
    CURRENT_CRON=$(crontab -l 2>/dev/null || true)
    
    # Remove Gauge entries (between markers)
    NEW_CRON=$(echo "$CURRENT_CRON" | sed '/# Gauge Autonomous Operation/,/autonomous_research\.py research/d')
    
    # Update crontab
    echo "$NEW_CRON" | crontab -
    
    echo "✓ CRON jobs removed"
}

# Dry run - show what would be added
dry_run() {
    echo "=== DRY RUN: Would add these CRON entries ==="
    echo ""
    echo "$CRON_ENTRIES"
    echo ""
    echo "=== Current crontab ==="
    crontab -l 2>/dev/null || echo "(empty)"
}

# Parse arguments
case "${1:-}" in
    --help|-h)
        show_help
        exit 0
        ;;
    --dry-run)
        check_prerequisites
        dry_run
        exit 0
        ;;
    --remove)
        remove_cron
        exit 0
        ;;
    "")
        check_prerequisites
        install_cron
        exit 0
        ;;
    *)
        echo "Error: Unknown option $1"
        echo "Run with --help for usage"
        exit 1
        ;;
esac
